version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=IgST3mp!482

  igsmarket.api:
    image: ${DOCKER_REGISTRY-}igsmarketapi
    build:
      context: .
      dockerfile: IgsMarket.Api/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db